# eureka-statefulset.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    app: eureka-service
spec:
  ports:
    - port: 8761                                    # service对外提供服务的端口
      targetPort: 8761
      nodePort: 8761      #如果不用映射到宿主机端口，则不需要加这个配置 
      name: eureka-service
  # clusterIP: None
  type: NodePort
  selector:
    app: eureka-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka-server
spec:
  serviceName: eureka-service
  replicas: 3
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: registry.cn-hangzhou.aliyuncs.com/zakiis/eureka:0.0.5
          ports:
            - containerPort: 8761
          resources:
            limits:
              cpu: "2"
              memory: 1.5Gi
            requests:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8761
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            tcpSocket: 
               port: 8761
            initialDelaySeconds: 25
            periodSeconds: 3
            failureThreshold: 3
            successThreshold: 1
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: APP_TIMEZONE
              value: GMT+8
            - name: EUREKA_SERVER
              value: "http://eureka-server-0.eureka-service:8761/eureka/,http://eureka-server-1.eureka-service:8761/eureka/,http://eureka-server-2.eureka-service:8761/eureka/"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: ${MY_POD_NAME}
  podManagementPolicy: "Parallel"